INSERT INTO Training(title, trainingType, link, trainingDescription) VALUES
("Coaching - Foundation","Selective","https://www.pluralsight.com/","Coaching is a form of development in which an experienced person, called a coach, supports a learner or client in achieving a specific personal or professional goal by providing training and guidance. The learner is sometimes called a coachee. \nOccasionally, coaching may mean an informal relationship between two people, of whom one has more experience and expertise than the other and offers advice and guidance as the latter learns; \n but coaching differs from mentoring by focusing on specific tasks or objectives, as opposed to more general goals or overall development. "),
("People Manager Toolkit: Performance","Mandatory","https://www.pluralsight.com/","People management is the management of subordinates in an organization. Often, large organizations have many of these functions performed by a specialist department, such as personnel or human resources, but all line managers are still required to supervise and administer the activities and ensure the well-being of the staff that report to them."),
("Coaching - Intermediate","Elective","https://www.pluralsight.com/","Coaching is a form of development in which an experienced person, called a coach, supports a learner or client in achieving a specific personal or professional goal by providing training and guidance. The learner is sometimes called a coachee. \nOccasionally, coaching may mean an informal relationship between two people, of whom one has more experience and expertise than the other and offers advice and guidance as the latter learns; \n but coaching differs from mentoring by focusing on specific tasks or objectives, as opposed to more general goals or overall development."),
("Presentation Skills","Selective","https://www.pluralsight.com/","A presentation is the process of presenting a topic to an audience. It is typically a demonstration, introduction, lecture, or speech meant to inform, persuade, inspire, motivate, or to build good will or to present a new idea or product. \n A presentation program is often used to generate the presentation content, some of which also allow presentations to be developed collaboratively, e.g. using the Internet by geographically disparate collaborators. Presentation viewers can be used to combine content from different sources into one presentation. Some of the popular presentation products used across the globe are offered by Apple and Microsoft."),
("Interview Skills - Foundation","Elective","https://www.pluralsight.com/","An interview is a conversation where questions are asked and answers are given. \n In common parlance, the word interview refers to a one-on-one conversation between an interviewer and an interviewee. The interviewer asks questions to which the interviewee responds, usually so information may be transferred from interviewee to interviewer (and any other audience of the interview). \n Sometimes, information can be transferred in both directions. It is a communication, unlike a speech, which produces a one-way flow of information."),
("Managing Teams Effectively","Mandatory","https://www.pluralsight.com/","Team management is the ability of an individual or an organization to administer and coordinate a group of individuals to perform a task. Team management involves teamwork, communication, objective setting and performance appraisals. Moreover, team management is the capability to identify problems and resolve conflicts within a team. There are various methods and leadership styles a team manager can take to increase personnel productivity and build an effective team."),
("Trainee Development Program","Mandatory","https://www.pluralsight.com/","Training and development involves improving the effectiveness of organizations and the individuals and teams within them. \n Training may be viewed as related to immediate changes in organizational effectiveness via organized instruction, while development is related to the progress of longer-term organizational and employee goals."),
("Apprentice Development Program","Mandatory","https://www.pluralsight.com/","An apprenticeship is a system of training a new generation of practitioners of a trade or profession with on-the-job training and often some accompanying study (classroom work and reading). Apprenticeships can also enable practitioners to gain a license to practice in a regulated profession. Most of their training is done while working for an employer who helps the apprentices learn their trade or profession, in exchange for their continued labor for an agreed period after they have achieved measurable competencies.");
