INSERT INTO Capability(capName,leadId,jfid)
VALUES("Architect","1",1),
VALUES("Software Engineering","1",1),
VALUES("Data Engineering","1",1),
VALUES("Infrastructure","1",1),
VALUES("Business Development","2",1),
VALUES("Account Management","2",2),
VALUES("Pre Sales & Bid Management","2",2),
VALUES("Product","3",3),
VALUES("HCM","3",3),
VALUES("Agile","3",3),
VALUES("Research","4",4),
VALUES("Service Design","4",4),
VALUES("Creative Design","4",4),
VALUES("U X Design","4",4),
VALUES("Project Management","5",5),
VALUES("Support Management","5",5),
VALUES("Finance & P M O","6",6),
VALUES("Commercial","6",6),
VALUES("Systems","6",6),
VALUES("People","6",6),
VALUES("Facilities","6",6),
VALUES("Administration","6",6)
