INSERT INTO Capability(capName,leadId,jfid) VALUES
("Architect",1,1),
("Ops",1,1),
("Testing",1,1),
("Analytics",1,1),
("Integration",1,1),
("Product Specialist",1,1),
("Product Support",1,1),
("Technical Specialist",1,1),
("Cyber Security",1,1),
("Software Engineering",1,1),
("Data Engineering",1,1),
("Infrastructure",1,1),
("Business Development",2,2),
("Account Management",2,2),
("Sales",2,2),
("Inside Sales Development",2,2),
("Marketing",2,2),
("Pre Sales & Bid Management",2,2),
("Product",3,3),
("HCM",3,3),
("Agile",3,3),
("Research",4,4),
("Service Design",4,4),
("Creative Design",4,4),
("U X Design",4,4),
("Project Management",5,5),
("Support Management",5,5),
("Finance & P M O",6,6),
("Commercial",6,6),
("Systems",6,6),
("People",6,6),
("Facilities",6,6),
("Administration",6,6);

("Administration",6,6),
("Travel",6,6),
("Strategy",6,6)
