INSERT INTO Training(title, trainingType, link, trainingDescription) VALUES
("Coaching - Foundation","Selective","https://www.pluralsight.com/","Lorem Ipsum eget enim quis, vulputate imperdiet elit. Phasellus id faucibus justo, fermentum faucibus leo. Vestibulum congue justo viverra malesuada suscipit. Curabitur laoreet hendrerit pretium. Integer ligula massa, eleifend id mattis ut, porta eu nisi. Integer ligula nibh, iaculis et suscipit sed, laoreet quis metus. Duis congue dignissim hendrerit. Donec venenatis arcu quis viverra molestie."),
("People Manager Toolkit: Performance","Mandatory","https://www.pluralsight.com/","Lorem Ipsum eget enim quis, vulputate imperdiet elit. Phasellus id faucibus justo, fermentum faucibus leo. Vestibulum congue justo viverra malesuada suscipit. Curabitur laoreet hendrerit pretium. Integer ligula massa, eleifend id mattis ut, porta eu nisi. Integer ligula nibh, iaculis et suscipit sed, laoreet quis metus. Duis congue dignissim hendrerit. Donec venenatis arcu quis viverra molestie. Lorem Ipsum"),
("Coaching - Intermediate","Elective","https://www.pluralsight.com/","Lorem Ipsum eget enim quis, vulputate imperdiet elit. Phasellus id faucibus justo, fermentum faucibus leo. Vestibulum congue justo viverra malesuada suscipit. Curabitur laoreet hendrerit pretium. Integer ligula massa, eleifend id mattis ut, porta eu nisi. Integer ligula nibh, iaculis et suscipit sed, laoreet quis metus. Duis congue dignissim hendrerit. Donec venenatis arcu quis viverra molestie. Lorem Ipsum"),
("Presentation Skills","Selective","https://www.pluralsight.com/","Lorem Ipsum eget enim quis, vulputate imperdiet elit. Phasellus id faucibus justo, fermentum faucibus leo. Vestibulum congue justo viverra malesuada suscipit. Curabitur laoreet hendrerit pretium. Integer ligula massa, eleifend id mattis ut, porta eu nisi. Integer ligula nibh, iaculis et suscipit sed, laoreet quis metus. Duis congue dignissim hendrerit. Donec venenatis arcu quis viverra molestie. Lorem Ipsum"),
("Interview Skills - Foundation","Elective","https://www.pluralsight.com/","Lorem Ipsum eget enim quis, vulputate imperdiet elit. Phasellus id faucibus justo, fermentum faucibus leo. Vestibulum congue justo viverra malesuada suscipit. Curabitur laoreet hendrerit pretium. Integer ligula massa, eleifend id mattis ut, porta eu nisi. Integer ligula nibh, iaculis et suscipit sed, laoreet quis metus. Duis congue dignissim hendrerit. Donec venenatis arcu quis viverra molestie. Lorem Ipsum"),
("Managing Teams Effectively","Mandatory","https://www.pluralsight.com/","Lorem Ipsum eget enim quis, vulputate imperdiet elit. Phasellus id faucibus justo, fermentum faucibus leo. Vestibulum congue justo viverra malesuada suscipit. Curabitur laoreet hendrerit pretium. Integer ligula massa, eleifend id mattis ut, porta eu nisi. Integer ligula nibh, iaculis et suscipit sed, laoreet quis metus. Duis congue dignissim hendrerit. Donec venenatis arcu quis viverra molestie. Lorem Ipsum"),
("Trainee Development Program","Mandatory","https://www.pluralsight.com/","Lorem Ipsum eget enim quis, vulputate imperdiet elit. Phasellus id faucibus justo, fermentum faucibus leo. Vestibulum congue justo viverra malesuada suscipit. Curabitur laoreet hendrerit pretium. Integer ligula massa, eleifend id mattis ut, porta eu nisi. Integer ligula nibh, iaculis et suscipit sed, laoreet quis metus. Duis congue dignissim hendrerit. Donec venenatis arcu quis viverra molestie. Lorem Ipsum"),
("Apprentice Development Program","Mandatory","https://www.pluralsight.com/","Lorem Ipsum eget enim quis, vulputate imperdiet elit. Phasellus id faucibus justo, fermentum faucibus leo. Vestibulum congue justo viverra malesuada suscipit. Curabitur laoreet hendrerit pretium. Integer ligula massa, eleifend id mattis ut, porta eu nisi. Integer ligula nibh, iaculis et suscipit sed, laoreet quis metus. Duis congue dignissim hendrerit. Donec venenatis arcu quis viverra molestie. Lorem Ipsum");
