INSERT INTO JobFamily(title,capId)
VALUES("Architect","1"),
VALUES("Software Engineering","1"),
VALUES("Data Engineering","1"),
VALUES("Infrastructure","1"),
VALUES("Business Development","2"),
VALUES("Account Management","2"),
VALUES("Pre Sales & Bid Management","2"),
VALUES("Product","3"),
VALUES("HCM","3"),
VALUES("Agile","3"),
VALUES("Research","4"),
VALUES("Service Design","4"),
VALUES("Creative Design","4"),
VALUES("U X Design","4"),
VALUES("Project Management","5"),
VALUES("Support Management","5"),
VALUES("Finance & P M O","6"),
VALUES("Commercial","6"),
VALUES("Systems","6"),
VALUES("People","6"),
VALUES("Facilities","6"),
VALUES("Administration","6")
