INSERT INTO Job(title,speclink,summary,responsibilities,bandId,jfid)
/* The "|" character is used to seperate responsbilities */
VALUES("Software Engineer","https://kainossoftwareltd.sharepoint.com/people.old/Shared%20Documents/Forms/AllItems.aspx?id=%2Fpeople.old%2FShared%20Documents%2FJob%20Descriptions%2FSoftware%20Engineering%2FJob%20Specification%20-%20Senior%20Software%20Engineer%20-%20Senior%20Associate.pdf&parent=%2Fpeople.old%2FShared%20Documents%2FJob%20Descriptions%2FSoftware%20Engineering&embed=%7B%22o%22%3A%22https%3A%2F%2Fkainossoftwareltd.sharepoint.com%22%2C%22id%22%3A%225396a260-dd7d-201b-6ccb-41b66038ed6f%22%2C%22af%22%3Atrue%7D","Delivers with limited supervision, trusted to make tactical decisions.","Make your line manager aware if you think someone may be considering leaving the company",5,2),
VALUES("Software Engineer","https://kainossoftwareltd.sharepoint.com/people.old/Shared%20Documents/Forms/AllItems.aspx?id=%2Fpeople.old%2FShared%20Documents%2FJob%20Descriptions%2FSoftware%20Engineering%2FJob%20Specification%20-%20Software%20Engineer%20-%20Trainee.pdf&parent=%2Fpeople.old%2FShared%20Documents%2FJob%20Descriptions%2FSoftware%20Engineering&embed=%7B%22o%22%3A%22https%3A%2F%2Fkainossoftwareltd.sharepoint.com%22%2C%22id%22%3A%22709cc3d3-3d67-366d-0494-2294bd2efe82%22%2C%22af%22%3Atrue%7D","Graduate entry level, here to learn, but primarily to contribute to projects.","Represent Kainos at careers fairs or Kainos open evenings events if invited |Immediately tell your manager if your tasks are not going to be complete within the expected timeframe",8,2),
VALUES("Technical Architect","https://kainossoftwareltd.sharepoint.com/people.old/Shared%20Documents/Forms/AllItems.aspx?id=%2Fpeople.old%2FShared%20Documents%2FJob%20Descriptions%2FArchitect%2FJob%20Specification%20-%20Technical%20Architect%20-%20Consultant.pdf&parent=%2Fpeople.old%2FShared%20Documents%2FJob%20Descriptions%2FArchitect&embed=%7B%22o%22%3A%22https%3A%2F%2Fkainossoftwareltd.sharepoint.com%22%2C%22id%22%3A%22932a1636-659e-5e67-d82c-e6d2b0bacede%22%2C%22af%22%3Atrue%7D","Expert in their field, is consulted by others, supervises others, works well even if under pressure, effectively coaches people.","Be an active career coach and to escalate to their line manager if stretch goals are not set for your coachees |Ensure that your coachee has received an appraisal and regular feedback and to escalate to HR if this is not the case",4,1),
VALUES("Lead Data Engineer","https://kainossoftwareltd.sharepoint.com/people.old/Shared%20Documents/Forms/AllItems.aspx?id=%2Fpeople.old%2FShared%20Documents%2FJob%20Descriptions%2FData%20Engineering%2FJob%20Specification%20-%20Lead%20Data%20Engineer%20-%20Consultant.pdf&parent=%2Fpeople.old%2FShared%20Documents%2FJob%20Descriptions%2FData%20Engineering&embed=%7B%22o%22%3A%22https%3A%2F%2Fkainossoftwareltd.sharepoint.com%22%2C%22id%22%3A%22ee9425af-a906-5e23-6f5a-30139e260fb2%22%2C%22af%22%3Atrue%7D","Expert in their field, is consulted by others, supervises others, works well even if under pressure, effectively coaches people.","Ensure that your coachee has received an appraisal and regular feedback and to escalate to HR if this is not the case", 5,3),
VALUES("Infrastructure Engineer"," ","Delivers with limited supervision, trusted to make tactical decisions.","Make your line manager aware if you think someone may be considering leaving the company",4,4),
VALUES("Account Manager","","Serves the company's commercial and delivery interests, owns single initiatives or projects, advocates effective coaching and ensures that it happens.","Provide anytime performance feedback on Workday to each of your team members at least once a quarter",4,6),
VALUES("Business Development Director"," ","Recognised leader and developer of Kainos talent, continuously improves Kainos, comfortable in novel situations, owns multiple initiatives, accountable for delivery at Programme level.","Be a Training Course Sponsor and deliver training in the Discover, Explore and Inspire schools",4,5),
VALUES("Presales Manager"," ","Serves the company's commercial and delivery interests, owns single initiatives or projects, advocates effective coaching and ensures that it happens.","Develop talent within your team, ensuring SMARTER stretch and project goals are clearly defined",4,7),
VALUES("Product Principle"," ","Recognised leader and developer of Kainos talent, continuously improves Kainos, comfortable in novel situations, owns multiple initiatives, accountable for delivery at Programme level.",3,8),
VALUES("HCM Consultant","https://kainossoftwareltd.sharepoint.com/:w:/r/people.old/_layouts/15/Doc.aspx?sourcedoc=%7B15A7B80A-9B8B-42DA-8A82-ACBD338C536A%7D&file=Job%20Specification%20-%20Workday%20Consultant%20Senior%20Associate%20Level_LT.docx&action=default&mobileredirect=true","Delivers with limited supervision, trusted to make tactical decisions.","Make your line manager aware if you think someone may be considering leaving the company",6,9),
